<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition=" '$(LibraryVersion)' != '' or '$(TargetFramework)' == 'net10.0' " >
    <PackageReference Include="System.ServiceModel.Http" VersionOverride="$(LibraryVersion)" />
    <PackageReference Include="System.ServiceModel.NetTcp" VersionOverride="$(LibraryVersion)" />
  </ItemGroup>
  <ItemGroup Condition=" '$(LibraryVersion)' == '' and ( '$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'net8.0' ) " >
    <PackageReference Include="System.ServiceModel.Http" VersionOverride="8.1.2" />
    <PackageReference Include="System.ServiceModel.NetTcp" VersionOverride="8.1.2" />
  </ItemGroup>
  <ItemGroup Condition=" '$(LibraryVersion)' == '' and ( '$(TargetFramework)' == 'net7.0' or '$(TargetFramework)' == 'net6.0' ) " >
    <PackageReference Include="System.ServiceModel.Http" VersionOverride="6.2.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" VersionOverride="6.2.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>
</Project>
